export const assets = {
  loginBg: "/assets/edutic-art/login-sky-islands-bg.png",
  homeBg: "/assets/edutic-art/sky-soft-bg.png",
  gameplayBg: "/assets/edutic-art/gameplay-bg.png",

  // Male mascot (new robot art delivered via /Images-new/, processed with real alpha).
  mascotMaleWave: "/assets/edutic-art/mascot-wave.png",
  mascotMaleJump: "/assets/edutic-art/mascot-jump.png",
  mascotMaleProud: "/assets/edutic-art/mascot-proud.png",
  mascotMaleLaptop: "/assets/edutic-art/mascot-laptop.png",
  mascotMaleNatural: "/assets/edutic-art/mascot-natural.png",

  // Female mascot — original transparent art.
  mascotFemaleWave: "/assets/edutic-art/mascot-women-wave.png",
  mascotFemaleLaptop: "/assets/edutic-art/mascot-women-laptop.png",

  worldsIsland1: "/assets/processed/worlds-island1-transparent.png",
  worldsIsland2: "/assets/processed/worlds-island2-transparent.png",
  worldsIsland3: "/assets/processed/worlds-island3-transparent.png",
  worldsIsland4: "/assets/processed/worlds-island4-transparent.png",
  worldsIsland5: "/assets/edutic-art/world-island5.png",
  island1: "/assets/edutic-art/island1.png",
  island2: "/assets/edutic-art/island2.png",
  island3: "/assets/edutic-art/island3.png",
  island4: "/assets/edutic-art/island4.png",
  island5: "/assets/edutic-art/island5.png",
  shipFront: "/assets/edutic-art/spaceships/ship-front.png",
  shipBack: "/assets/edutic-art/spaceships/ship-back.png",
  shipLeft: "/assets/edutic-art/spaceships/ship-left.png",
  shipRight: "/assets/edutic-art/spaceships/ship-right.png",
  shipDiagonalLeft: "/assets/edutic-art/spaceships/ship-diagonal-left.png",
  shipDiagonalRight: "/assets/edutic-art/spaceships/ship-diagonal-right.png",

  /* Island 5 props — used by SkillLevelView for the mouse-skill levels. */
  i5Star:    "/assets/edutic-art/island5/star.png",
  i5Apple:   "/assets/edutic-art/island5/apple.png",
  i5Rabbit:  "/assets/edutic-art/island5/rabbit.png",
  i5Ball:    "/assets/edutic-art/island5/ball.png",
  i5Shot:    "/assets/edutic-art/island5/shot.png",
  i5Penguin: "/assets/edutic-art/island5/penguin.png",
  i5Bag:     "/assets/edutic-art/island5/bag.png",
  i5Chest:   "/assets/edutic-art/island5/cofre.png",
  i5Potion:  "/assets/edutic-art/island5/potion.png",
  i5Apps:    "/assets/edutic-art/island5/apps.png",
  i5WindowControls: "/assets/edutic-art/island5/cerrar-maximizar-minimizar-ventana.png",
  i5Message: "/assets/edutic-art/island5/mensaje.png",
  i5Notes:   "/assets/edutic-art/island5/notas.png",
  i5WindowMedia: "/assets/edutic-art/island5/ventana-mismedios.png",
  i5BrowserTabs: "/assets/edutic-art/island5/pestanas-explorador-videos-dibujos.png",
  i5DrawingsWindow: "/assets/edutic-art/island5/dibujos-ventana.png",
  i5Mouse:   "/assets/edutic-art/island5/mouse.png",
  i5CastleVertical: "/assets/edutic-art/island5/castillo-vertical.png",
  i5CastleSquare:   "/assets/edutic-art/island5/castillo-cuadrada.png",
  i5ZoomBtns:       "/assets/edutic-art/island5/zoom-mas-menos.png",
};
