#!/usr/bin/env python3
"""
process_typely_assets.py — shrink the web WebP assets that make the world map
and island-detail screens heavy on first paint.

Mirrors the pattern of process_mecano.py / process_ships.py, but instead of
reading the original PNGs it RE-EXPORTS the already-web WebP files in
public/ to smaller dimensions. The source PNGs in Images/ and Images-new/ are
never touched.

Rules:
  - Downscale so the LONGEST edge == the target for that family (only if the
    image is currently larger). Aspect ratio preserved.
  - Transparency preserved (RGBA in → RGBA out).
  - Re-encode WebP at the family quality, method=6 (best size/speed tradeoff).
  - Idempotent + safe: the new file is written ONLY if it is smaller than the
    existing one, so re-running never bloats an asset.
  - Prints a per-file report and writes public/assets/.sizes-report.txt.

Run:  python Images-new/process_typely_assets.py
"""
from __future__ import annotations

import glob
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
REPORT = os.path.join(PUBLIC, "assets", ".sizes-report.txt")

# (glob relative to public/, longest-edge target px, webp quality)
FAMILIES = [
    # World-map thumbnails — shown small (≈14–22rem), so a 720px longest edge
    # is plenty and cuts ~60% of the bytes.
    ("assets/processed/worlds-island*-transparent.webp", 720, 72),
    ("assets/edutic-art/world-island5.webp", 720, 72),
    ("typely_islands_webp/background-island*.webp", 720, 72),
    # Island-detail full-screen backgrounds — behind glass panels, 1280 is ample.
    ("assets/edutic-art/island[1-5].webp", 1280, 75),
    # Ships — small markers on the detail map.
    ("assets/edutic-art/spaceships/ship-*.webp", 256, 72),
]


def human(n: int) -> str:
    return f"{n / 1024:.1f} KB"


def process_one(path: str, max_edge: int, quality: int) -> tuple[int, int]:
    """Returns (old_bytes, new_bytes). new == old when nothing was written."""
    old_bytes = os.path.getsize(path)
    with Image.open(path) as im:
        im.load()
        has_alpha = im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info)
        im = im.convert("RGBA" if has_alpha else "RGB")
        w, h = im.size
        longest = max(w, h)
        if longest > max_edge:
            scale = max_edge / longest
            im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
        tmp = path + ".tmp.webp"
        im.save(tmp, "WEBP", quality=quality, method=6)
    new_bytes = os.path.getsize(tmp)
    # Only adopt the new file if it actually saves bytes.
    if new_bytes < old_bytes:
        os.replace(tmp, path)
        return old_bytes, new_bytes
    os.remove(tmp)
    return old_bytes, old_bytes


def main() -> None:
    lines: list[str] = []
    total_old = total_new = 0
    for pattern, max_edge, quality in FAMILIES:
        for path in sorted(glob.glob(os.path.join(PUBLIC, pattern))):
            old, new = process_one(path, max_edge, quality)
            total_old += old
            total_new += new
            rel = os.path.relpath(path, PUBLIC)
            mark = "-" if new < old else "="
            line = f"{mark} {rel:<58} {human(old):>10} => {human(new):>10}"
            print(line)
            lines.append(line)

    saved = total_old - total_new
    summary = (
        f"\nTotal: {human(total_old)} -> {human(total_new)}  "
        f"(saved {human(saved)}, {100 * saved / total_old:.0f}%)"
        if total_old
        else "No files matched."
    )
    print(summary)
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w", encoding="utf-8") as f:
        f.write("TYPELY web asset sizes (regenerated by process_typely_assets.py)\n")
        f.write("\n".join(lines))
        f.write("\n" + summary.strip() + "\n")


if __name__ == "__main__":
    main()
